# Generated by Django 3.2.3 on 2021-06-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210606_1505'),
        ('actors', '0002_actors_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='movie',
            field=models.ManyToManyField(related_name='actors', to='movies.Movie'),
        ),
    ]
