# Generated by Django 3.2.3 on 2021-06-06 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_alter_actors_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='actors',
            constraint=models.UniqueConstraint(fields=('name', 'surname', 'birthday'), name='unique_actor'),
        ),
    ]
