# Generated by Django 3.2.3 on 2021-06-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_alter_actors_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='image',
            field=models.ImageField(default='none', upload_to='images'),
            preserve_default=False,
        ),
    ]
