# Generated by Django 3.2.3 on 2021-06-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0007_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='actor',
        ),
    ]
