# Generated by Django 3.2.3 on 2021-06-09 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0009_ratings_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
