# Generated by Django 3.2.3 on 2021-06-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0010_actors_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='IMDB_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='actors',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
