# Generated by Django 3.2.3 on 2021-06-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0011_auto_20210612_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actors',
            name='IMDB_rating',
        ),
        migrations.AddField(
            model_name='actors',
            name='Filmweb_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
