# Generated by Django 3.2.3 on 2021-10-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_auto_20211012_1336'),
        ('actors', '0014_auto_20210617_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='Filmweb_rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='(1 - 9,9)', max_digits=2),
        ),
        migrations.AlterField(
            model_name='actors',
            name='birthday',
            field=models.DateField(help_text='(YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='description',
            field=models.TextField(default='', help_text='Max - 500 characters', max_length=500),
        ),
        migrations.AlterField(
            model_name='actors',
            name='image',
            field=models.ImageField(height_field=50, upload_to='images', width_field=50),
        ),
        migrations.AlterField(
            model_name='actors',
            name='movie',
            field=models.ManyToManyField(related_name='actors', to='movies.Movie', verbose_name='Movies'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='(1 - 5)'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='review',
            field=models.TextField(help_text='Max - 150 characters', max_length=150),
        ),
    ]
