# Generated by Django 3.2.3 on 2021-10-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0015_auto_20211012_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='image',
            field=models.ImageField(height_field='50', upload_to='images', width_field='50'),
        ),
    ]
