# Generated by Django 3.2.3 on 2021-10-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0018_alter_actors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
