# Generated by Django 3.2.3 on 2021-06-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210601_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Action'), (4, 'Fantasy'), (1, 'Adventure'), (10, 'Western'), (8, 'Science fiction'), (7, 'Romance'), (9, 'Thriller'), (2, 'Comedy'), (3, 'Crime and mystery'), (5, 'Historical'), (11, 'Other'), (6, 'Horror')], default=11),
        ),
    ]
