# Generated by Django 3.2.3 on 2021-06-01 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_auto_20210601_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(8, 'Science fiction'), (0, 'Action'), (2, 'Comedy'), (10, 'Western'), (11, 'Other'), (3, 'Crime and mystery'), (7, 'Romance'), (1, 'Adventure'), (5, 'Historical'), (4, 'Fantasy'), (6, 'Horror'), (9, 'Thriller')], default=11),
        ),
    ]
