# Generated by Django 3.2.3 on 2021-06-06 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210601_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(9, 'Thriller'), (3, 'Crime and mystery'), (11, 'Other'), (6, 'Horror'), (1, 'Adventure'), (7, 'Romance'), (4, 'Fantasy'), (0, 'Action'), (2, 'Comedy'), (5, 'Historical'), (10, 'Western'), (8, 'Science fiction')], default=11),
        ),
    ]
