# Generated by Django 3.2.3 on 2021-06-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210606_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Horror'), (0, 'Action'), (9, 'Thriller'), (11, 'Other'), (8, 'Science fiction'), (3, 'Crime and mystery'), (5, 'Historical'), (7, 'Romance'), (4, 'Fantasy'), (2, 'Comedy'), (10, 'Western'), (1, 'Adventure')], default=11),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(4, 4), (5, 5), (3, 3), (2, 2), (0, 0), (1, 1)], default=0),
        ),
    ]
