# Generated by Django 3.2.3 on 2021-06-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210606_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Adventure'), (2, 'Comedy'), (3, 'Crime and mystery'), (11, 'Other'), (0, 'Action'), (9, 'Thriller'), (6, 'Horror'), (10, 'Western'), (8, 'Science fiction'), (5, 'Historical'), (7, 'Romance'), (4, 'Fantasy')], default=11),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movie_unique',
        ),
    ]
