# Generated by Django 3.2.3 on 2021-06-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20210606_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Western'), (6, 'Horror'), (3, 'Crime and mystery'), (4, 'Fantasy'), (7, 'Romance'), (0, 'Action'), (8, 'Science fiction'), (2, 'Comedy'), (9, 'Thriller'), (11, 'Other'), (5, 'Historical'), (1, 'Adventure')], default=11),
        ),
        migrations.AlterModelTable(
            name='movie',
            table=None,
        ),
    ]
