# Generated by Django 3.2.3 on 2021-06-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20210606_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Action'), (1, 'Adventure'), (9, 'Thriller'), (4, 'Fantasy'), (3, 'Crime and mystery'), (7, 'Romance'), (10, 'Western'), (5, 'Historical'), (11, 'Other'), (6, 'Horror'), (8, 'Science fiction'), (2, 'Comedy')], default=11),
        ),
        migrations.AlterModelTable(
            name='movie',
            table=None,
        ),
    ]
