# Generated by Django 3.2.3 on 2021-06-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20210606_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Action'), (11, 'Other'), (1, 'Adventure'), (3, 'Crime and mystery'), (10, 'Western'), (6, 'Horror'), (4, 'Fantasy'), (5, 'Historical'), (8, 'Science fiction'), (2, 'Comedy'), (9, 'Thriller'), (7, 'Romance')], default=11),
        ),
    ]
