# Generated by Django 3.2.3 on 2021-06-06 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0014_alter_movie_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(11, 'Other'), (7, 'Romance'), (8, 'Science fiction'), (2, 'Comedy'), (9, 'Thriller'), (0, 'Action'), (5, 'Historical'), (1, 'Adventure'), (3, 'Crime and mystery'), (4, 'Fantasy'), (10, 'Western'), (6, 'Horror')], default=11),
        ),
        migrations.AlterField(
            model_name='movie',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
