# Generated by Django 3.2.3 on 2021-06-07 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0015_auto_20210606_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='stars',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Historical'), (7, 'Romance'), (1, 'Adventure'), (0, 'Action'), (9, 'Thriller'), (2, 'Comedy'), (6, 'Horror'), (4, 'Fantasy'), (10, 'Western'), (11, 'Other'), (8, 'Science fiction'), (3, 'Crime and mystery')], default=11),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
