# Generated by Django 3.2.3 on 2021-06-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20210609_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='x', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Action'), (1, 'Adventure'), (2, 'Comedy'), (3, 'Crime and mystery'), (4, 'Fantasy'), (5, 'Historical'), (6, 'Horror'), (7, 'Romance'), (8, 'Science fiction'), (9, 'Thriller'), (10, 'Western'), (11, 'Other')], default=11),
        ),
        migrations.AlterField(
            model_name='movie',
            name='yt_id',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='movie',
            name='yt_title',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='movie',
            name='yt_url',
            field=models.CharField(help_text='Paste YouTube URL address or add it using search bar on the right', max_length=225, verbose_name='Trailer - YouTube URL'),
        ),
    ]
