# Generated by Django 3.2.3 on 2021-06-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20210609_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='IMDB_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Action'), (1, 'Adventure'), (2, 'Comedy'), (3, 'Crime and mystery'), (4, 'Drama'), (5, 'Fantasy'), (6, 'Historical'), (7, 'Horror'), (8, 'Romance'), (9, 'Science fiction'), (10, 'Thriller'), (11, 'Western'), (12, 'Other')], default=12),
        ),
    ]
