# Generated by Django 3.2.3 on 2021-10-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_auto_20210617_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='IMDB_rating',
            field=models.DecimalField(decimal_places=1, help_text='(1 - 9,9)', max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(help_text='Max - 500 characters', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.DateField(help_text='(YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Max - 150 characters', max_length=32),
        ),
        migrations.AlterField(
            model_name='movie',
            name='yt_url',
            field=models.CharField(help_text='Paste YouTube URL address or add it using our search bar', max_length=225, verbose_name='Trailer - YouTube URL'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='(1 - 5)'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.TextField(help_text='Max - 150 characters', max_length=150),
        ),
    ]
